### ISSUE TITLE
Using GenerateStorageOrder

### ISSUE THREAD

**Issue by jimmychu0807** [hkwtf/cess-go-sdk-tutorial#1]
@AstaFrode
I have updated the **cess-go-sdk** lib [to 0.0.77](https://github.com/hkwtf/cess-go-sdk-tutorial/blob/jc/dev/go.mod#L6). I then run the [simple-client_test here](https://github.com/hkwtf/cess-go-sdk-tutorial/blob/jc/dev/tutorials/simple-client_test.go#L79-L94). Running this example returns the following error:

```
Get into TestMain
=== RUN   TestSimpleClient
--- PASS: TestSimpleClient (1.90s)
=== RUN   TestDeOSS
txHash:


owner: [99 88 107 100 88 111 107 99 77 97 51 50 66 65 89 107 109 115 71 106 104 82 71 65 50 67 89 109 76 85 78 50 112 113 54 57 85 56 107 57 116 97 88 115 81 80 72 71 112]

res: 

err: invalid account ID bytes

--- PASS: TestDeOSS (1.83s)
PASS
ok  	github.com/CESSProject/cess-go-sdk-tutorial/tutorials	3.765s
```

The error seems to be returned from [this line in `file.go`](https://github.com/CESSProject/cess-go-sdk/blob/main/chain/file.go#L137). What do you expect the owner bytes to be like?

**Comment by jimmychu0807** [comment]
@AstaFrode 那為什麼我這兩行：
- https://github.com/hkwtf/cess-go-sdk-tutorial/blob/360b57acc428de8e2f81e08364b303ad373e328a/tutorials/simple-client_test.go#L78
- https://github.com/hkwtf/cess-go-sdk-tutorial/blob/360b57acc428de8e2f81e08364b303ad373e328a/tutorials/simple-client_test.go#L102

總是報錯？
你 `git clone` 後,可執行 `make test` 執行測試用例。

**Comment by AstaFrode** [comment]
To create and fund your configured wallet account on the cess chain.
